#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BroodAutomaat.Resource", IsApplication=true)]

namespace BroodAutomaat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int Accent = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int Background = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int BakkerButton = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int SelectionBox = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int Title = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int TitleBackground = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int Title = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int TitlePadding = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int bakkerButtonMargin = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int bakkerButtonMarginActive = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int fontSize = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int HelpButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int LogoBakker = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int map = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int RadioBox = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int RadioBoxCustom = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int RadioBoxOn = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int RoundedButton = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int button_aanvullen = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int button_automaten = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int button_help = 2131230726;
			
			// aapt resource value: 0x7f08001a
			public const int button_login = 2131230746;
			
			// aapt resource value: 0x7f080005
			public const int button_logout = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int button_route = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int button_statistieken = 2131230723;
			
			// aapt resource value: 0x7f080011
			public const int distance1 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int distance2 = 2131230738;
			
			// aapt resource value: 0x7f080008
			public const int frameLayout1 = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int imageView1 = 2131230732;
			
			// aapt resource value: 0x7f08001b
			public const int imageView2 = 2131230747;
			
			// aapt resource value: 0x7f08000a
			public const int info_block = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int linearLayout1 = 2131230727;
			
			// aapt resource value: 0x7f080010
			public const int linearLayout2 = 2131230736;
			
			// aapt resource value: 0x7f080018
			public const int radioButtonAlle = 2131230744;
			
			// aapt resource value: 0x7f080015
			public const int radioButtonGrof = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int radioButtonLicht = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int radioButtonWit = 2131230743;
			
			// aapt resource value: 0x7f080014
			public const int radioGroup_broden = 2131230740;
			
			// aapt resource value: 0x7f08000e
			public const int range_value = 2131230734;
			
			// aapt resource value: 0x7f080000
			public const int root_bakker = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int root_main = 2131230731;
			
			// aapt resource value: 0x7f08000f
			public const int seekBar_range = 2131230735;
			
			// aapt resource value: 0x7f080009
			public const int textView2 = 2131230729;
			
			// aapt resource value: 0x7f080019
			public const int title_bakker = 2131230745;
			
			// aapt resource value: 0x7f08000d
			public const int title_straal = 2131230733;
			
			// aapt resource value: 0x7f080013
			public const int title_type = 2131230739;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Bakker = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int InformationUser = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int info_bakker_aanvullen = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int info_bakker_automaten = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int info_bakker_route = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int info_bakker_statistieken = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int info_home = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
